[package]
name = "tracing-test"
version = "0.1.0"
authors = ["Matthias Prechtl <m.sleepypanda@gmail.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tracing = "0.1"
